# 3.9 doesn't compile
#FROM rabbitmq:3.9-management 
# 3.10 works!
FROM rabbitmq:3.10-management
# 3.12 crashes
#FROM rabbitmq:3.12-management
# 3.11 works but syntax issues in admin console
#FROM rabbitmq:3.11-management 

RUN apt update && apt install -y gettext
